import React, {useState, useEffect} from 'react'
// Main Home page for displaying and searching AI-generated images
import {Loader, Card, FormField} from '../components'


/**
 * RenderCards component
 * Renders a list of Card components for each post in the data array.
 * If no data is present, displays a placeholder message.
 */
const RenderCards = ({data, title}) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post}/>)
  }

  return (
    <h2 className='mt-5 font-bold text-[#6469ff] text-xl uppercase'>
      CARD
    </h2>
  )

}

/**
 * Home component
 * Main page for displaying the community showcase and search functionality.
 */
const Home = () => {
  // State variables
  const [loading, setLoading] = useState(false); // Loading state for API requests
  const [allPost, setAllPost] = useState(null) // All posts fetched from the server
  const [searchText, setSearchText] = useState('') // Search input value
  const [searchedResults, setSearchedResults] = useState(null) // Filtered search results
  const [searchTimeout, setSearchTimeout] = useState(null) // Timeout for debounced search

  // Fetch all posts from the backend API on component mount
  useEffect(() => {
    const fetchPost = async() => {
      setLoading(true)
      try {
        const response = await fetch('http://localhost:8080/api/v1/posts', {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json'
          }
        })

        if (response.ok){
          const result = await response.json()
          // Reverse to show latest posts first
          setAllPost(result.data.reverse())
        }
        
      } catch (error) {
        alert(error)
        
      }finally{
        setLoading(false)
      }
    }

    fetchPost()
  }, [])

  /**
   * Handles changes in the search input.
   * Debounces the search to avoid excessive filtering.
   */
  const handleSearchChange = (e) => {
    setSearchText(e.target.value)

    setSearchTimeout(
      setTimeout(() => {

      const searchResults = allPost.filter((item) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()))

      setSearchedResults(searchResults)

    }, 500))
    
  } 

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          The Community Showcase
        </h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>
          Browse through a collection of imaginative and visually stunning images generated by Dall-E AI
        </p>
      </div>
      <div className='mt-16 '>
        {/* Search input field */}
        <FormField
          labelName='Search Post'
          type='text'
          name='text'
          placeholder='Search Post'
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>
      <div className='mt-10'>
        {loading ? 
        <div className='flex justify-center items-center'>
          {/* Loader while fetching posts */}
          <Loader/>
        </div> : 
        <>
          {searchText && (
            <h2 className='font-medium text-[#666e75] text-xl mb-3'> 
              Showing Results for 
              <span className='text-[#222328'>{searchText}</span>
            </h2>
          )}

          <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
            {/* Render filtered search results or all posts */}
            {searchText ? (
              <RenderCards data={searchedResults} title='No Search Results found'/>
            ) : (
              <RenderCards data={allPost} title='No Post Found'/>
            )}
          </div>
        </>
        }
      </div>
    </section>
  )
}

export default Home
